#include <iostream>
using namespace std;
 
int main()
{
    try  {
       throw 'a';
    }
   catch (char *excp)  {cout << "Caught " << excp;}
    //catch (int excp) {
        //cout << "Caught " << excp << endl;
    catch (...)  {
        cout << "Default Exception\n";
    }
    return 0;
}
